virus: "zika" ## IMPORTANT PARAMETER - used to name outputs

verbose: false

nthreads: 4 ## IMPORTANT PARAMETER - how many CPUs available?

data: ## IMPORTANT PARAMETERS - paths should be relative to the tutorial directory
  sequences: "data/sequences.fasta"
  metadata: "data/metadata.tsv"
  excluded_strains: "data/excluded_strains.txt"
  included_strains: "data/included_strains.txt"
  reference: "data/reference.gb"
  reference_name: "PF13/251013_18" # IMPORTANT PARAMETER - fill in the name of the reference sequence

filter:
  metadata_chunk_size: 100000,
  metadata_id_columns: "strain name"
  min_date: null,
  max_date: null,
  include_where: null,
  exclude_where: null,
  exclude_all: False,
  exclude_ambiguous_dates_by: null,
  min_length: 9000, ## IMPORTANT PARAMETER - recommend 90% of the total genome length
  non_nucleotide: False,

align:
  method: "mafft"
  remove_reference: False,
  fill_gaps: True,
  existing_alignment: null,

tree:
  method: "iqtree"
  substitution_model: "GTR"
  exclude_sites: null,
  override_default_args: False,

refine:
  branch_length_inference: "auto"
  clock_filter_iqd: 5,
  clock_rate: null,
  clock_std_dev: null,
  coalescent: null,
  covariance: True,
  date_confidence: False,
  date_format: "%Y-%m-%d"
  date_inference: "joint"
  divergence_units: "mutations"
  gen_per_year: null,
  keep_polytomies: True,
  keep_root: False,
  no_covariance: False,
  precision: "auto"
  root: "best"
  seed: null,
  timetree: True,
  use_fft: False,
  year_bounds: null,

ancestral:
  inference: "joint"
  infer_ambiguous: True,
  keep_overhangs: False,

traits:
  columns: "region country" # IMPORTANT PARAMETER - want to infer how metadata traits have changed over time (e.g., geographic movement)? Put the field name(s) here.
  confidence: null,
  sampling_bias_correction: null,
  weights: null,

export:
  auspice_config: null,
  build_url: null,
  colors: null,
  color_by_metadata: "region country division location gt num_date author" # IMPORTANT PARAMETER - which metadata fields should be offered as color-by options?
  description: null,
  geo_resolutions: "region country division location"
  include_root_sequence: False,
  lat_longs: null,
  maintainers: "Your name here <https://your-url-here>" # IMPORTANT PARAMETER - who are you, and where can people find you on the web? :)
  minify_json: False,
  panels: null,
  skip_validation: False,
  title: "Tutorial Nextstrain build for Zika virus" # IMPORTANT PARAMETER - title
