virus: "zika" ## IMPORTANT PARAMETER - used to name outputs

verbose: false

nthreads: 4 ## IMPORTANT PARAMETER - how many CPUs available?

data: ## IMPORTANT PARAMETERS - paths should be relative to the tutorial directory
  sequences: "data/sequences.fasta"
  metadata: "data/metadata.tsv"
  excluded_strains: "data/excluded_strains.txt"
  included_strains: "data/included_strains.txt"
  reference: "data/reference.gb"
  reference_name: "PF13/251013_18" # IMPORTANT PARAMETER - fill in the name of the reference sequence

filter:
  metadata_chunk_size: 100000
  metadata_id_columns: "strain name"
  min_length: 9000 ## IMPORTANT PARAMETER - recommend 90% of the total genome length
  # min_date: null
  # max_date: null
  # include_where: null
  # exclude_where: null
  # exclude_all_FLAG: False
  # exclude_ambiguous_dates_by: null
  # non_nucleotide_FLAG: False

align:
  method: "mafft"
  fill_gaps_FLAG: True
  # remove_reference_FLAG: False
  # existing_alignment: null

tree:
  method: "iqtree"
  substitution_model: "GTR"
  # exclude_sites: null
  # override_default_args: False

refine:
  branch_length_inference: "auto"
  clock_filter_iqd: 5
  covariance_FLAG: True
  date_confidence_FLAG: False
  date_format: "%Y-%m-%d"
  date_inference: "joint"
  divergence_units: "mutations"
  keep_polytomies_FLAG: True
  root: "best"
  timetree_FLAG: True
  use_fft_FLAG: False
  # clock_rate: null
  # clock_std_dev: null
  # coalescent: null
  # gen_per_year: null
  # keep_root_FLAG: False
  # no_covariance: False
  # precision: null
  # seed: null
  # year_bounds: null

ancestral:
  inference: "joint"
  infer_ambiguous_FLAG: True
  # keep_overhangs_FLAG: False

translate:
  # genes: null

traits:
  columns: "region country" # IMPORTANT PARAMETER - want to infer how metadata traits have changed over time (e.g. geographic movement)? Put the field name(s) here.
  # confidence_FLAG: null
  # sampling_bias_correction: null
  # weights: null

export: # IMPORTANT PARAMETERS for customizing display contained in the additional config file, auspice_config.json
  auspice_config: "auspice_config.json"
